[".oh-my-bash"]
    type = "archive"
    url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/fonts/iosevka-comfy"]
    type = "archive"
    url = "https://github.com/protesilaos/iosevka-comfy/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".local/share/fonts/SF-Mono"]
    type = "archive"
    url = "https://github.com/supercomputra/SF-Mono-Font/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".local/share/fonts/SF"]
    type = "archive"
    url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts/archive/master.tar.gz"
    exact = true
    stripComponents = 1
